import { MovieOrTVShow } from '../model';
import { firstTenMoviesOrTVShowsWithPoster } from './utils';

describe('firstTenMoviesOrTVShowsWithPoster', () => {
  it('returns an array of 10 MovieOrTVShow objects with poster property', () => {
    const similarMoviesOrTvShows: MovieOrTVShow[] = [
      {
        id: 1,
        title: 'Movie 1',
        poster_path: '/poster1.jpg',
        overview: 'Overview 1',
        release_date: '2022-02-22',
        vote_average: 7.5,
        backdrop_path: '/backdrop_path.jpg',
        genre_ids: [1, 3, 5],
        original_language: 'EN',
        popularity: 10,
        vote_count: 6,
      },
      {
        id: 2,
        title: 'Movie 2',
        poster_path: '/poster2.jpg',
        overview: 'Overview 2',
        release_date: '2022-02-22',
        vote_average: 8.0,
        backdrop_path: '/backdrop_path.jpg',
        genre_ids: [1, 23],
        original_language: 'EN',
        popularity: 10,
        vote_count: 6,
      },
      {
        id: 3,
        title: 'Movie 3',
        poster_path: '/poster3.jpg',
        overview: 'Overview 3',
        release_date: '2022-02-22',
        vote_average: 6.5,
        backdrop_path: '/backdrop_path.jpg',
        genre_ids: [23, 5],
        original_language: 'EN',
        popularity: 10,
        vote_count: 6,
      },
      {
        id: 4,
        title: 'Movie 1',
        poster_path: '/poster4.jpg',
        overview: 'Overview 1',
        release_date: '2022-02-22',
        vote_average: 7.5,
        backdrop_path: '/backdrop_path.jpg',
        genre_ids: [1, 3, 5],
        original_language: 'EN',
        popularity: 10,
        vote_count: 6,
      },
      {
        id: 5,
        title: 'Movie 2',
        poster_path: '/poster5.jpg',
        overview: 'Overview 2',
        release_date: '2022-02-22',
        vote_average: 8.0,
        backdrop_path: '/backdrop_path.jpg',
        genre_ids: [1, 23],
        original_language: 'EN',
        popularity: 10,
        vote_count: 6,
      },
      {
        id: 6,
        title: 'Movie 3',
        poster_path: '/poster6.jpg',
        overview: 'Overview 3',
        release_date: '2022-02-22',
        vote_average: 6.5,
        backdrop_path: '/backdrop_path.jpg',
        genre_ids: [23, 5],
        original_language: 'EN',
        popularity: 10,
        vote_count: 6,
      },
      {
        id: 7,
        title: 'Movie 1',
        poster_path: '/poster7.jpg',
        overview: 'Overview 1',
        release_date: '2022-02-22',
        vote_average: 7.5,
        backdrop_path: '/backdrop_path.jpg',
        genre_ids: [1, 3, 5],
        original_language: 'EN',
        popularity: 10,
        vote_count: 6,
      },
      {
        id: 8,
        title: 'Movie 2',
        poster_path: '/poster8.jpg',
        overview: 'Overview 2',
        release_date: '2022-02-22',
        vote_average: 8.0,
        backdrop_path: '/backdrop_path.jpg',
        genre_ids: [1, 23],
        original_language: 'EN',
        popularity: 10,
        vote_count: 6,
      },
      {
        id: 9,
        title: 'Movie 3',
        poster_path: '/poster9.jpg',
        overview: 'Overview 3',
        release_date: '2022-02-22',
        vote_average: 6.5,
        backdrop_path: '/backdrop_path.jpg',
        genre_ids: [23, 5],
        original_language: 'EN',
        popularity: 10,
        vote_count: 6,
      },
      {
        id: 10,
        title: 'Movie 3',
        poster_path: '/poster10.jpg',
        overview: 'Overview 3',
        release_date: '2022-02-22',
        vote_average: 6.5,
        backdrop_path: '/backdrop_path.jpg',
        genre_ids: [23, 5],
        original_language: 'EN',
        popularity: 10,
        vote_count: 6,
      },
      {
        id: 11,
        title: 'Movie 3',
        poster_path: null,
        overview: 'Overview 3',
        release_date: '2022-02-22',
        vote_average: 6.5,
        backdrop_path: '/backdrop_path.jpg',
        genre_ids: [23, 5],
        original_language: 'EN',
        popularity: 10,
        vote_count: 6,
      },
    ];

    const result = firstTenMoviesOrTVShowsWithPoster(similarMoviesOrTvShows);

    expect(result.length).toBe(10);
    expect(result[0]).toEqual({
      id: 1,
      title: 'Movie 1',
      poster_path: '/poster1.jpg',
      overview: 'Overview 1',
      release_date: '2022-02-22',
      vote_average: 7.5,
      backdrop_path: '/backdrop_path.jpg',
      genre_ids: [1, 3, 5],
      original_language: 'EN',
      popularity: 10,
      vote_count: 6,
    });
    expect(result[1]).toEqual({
      id: 2,
      title: 'Movie 2',
      poster_path: '/poster2.jpg',
      overview: 'Overview 2',
      release_date: '2022-02-22',
      vote_average: 8.0,
      backdrop_path: '/backdrop_path.jpg',
      genre_ids: [1, 23],
      original_language: 'EN',
      popularity: 10,
      vote_count: 6,
    });
    expect(result[2]).toEqual({
      id: 3,
      title: 'Movie 3',
      poster_path: '/poster3.jpg',
      overview: 'Overview 3',
      release_date: '2022-02-22',
      vote_average: 6.5,
      backdrop_path: '/backdrop_path.jpg',
      genre_ids: [23, 5],
      original_language: 'EN',
      popularity: 10,
      vote_count: 6,
    });
    expect(result[3]).toEqual({
      id: 4,
      title: 'Movie 1',
      poster_path: '/poster4.jpg',
      overview: 'Overview 1',
      release_date: '2022-02-22',
      vote_average: 7.5,
      backdrop_path: '/backdrop_path.jpg',
      genre_ids: [1, 3, 5],
      original_language: 'EN',
      popularity: 10,
      vote_count: 6,
    });
    expect(result[4]).toEqual({
      id: 5,
      title: 'Movie 2',
      poster_path: '/poster5.jpg',
      overview: 'Overview 2',
      release_date: '2022-02-22',
      vote_average: 8.0,
      backdrop_path: '/backdrop_path.jpg',
      genre_ids: [1, 23],
      original_language: 'EN',
      popularity: 10,
      vote_count: 6,
    });
    expect(result[5]).toEqual({
      id: 6,
      title: 'Movie 3',
      poster_path: '/poster6.jpg',
      overview: 'Overview 3',
      release_date: '2022-02-22',
      vote_average: 6.5,
      backdrop_path: '/backdrop_path.jpg',
      genre_ids: [23, 5],
      original_language: 'EN',
      popularity: 10,
      vote_count: 6,
    });
    expect(result[6]).toEqual({
      id: 7,
      title: 'Movie 1',
      poster_path: '/poster7.jpg',
      overview: 'Overview 1',
      release_date: '2022-02-22',
      vote_average: 7.5,
      backdrop_path: '/backdrop_path.jpg',
      genre_ids: [1, 3, 5],
      original_language: 'EN',
      popularity: 10,
      vote_count: 6,
    });
    expect(result[7]).toEqual({
      id: 8,
      title: 'Movie 2',
      poster_path: '/poster8.jpg',
      overview: 'Overview 2',
      release_date: '2022-02-22',
      vote_average: 8.0,
      backdrop_path: '/backdrop_path.jpg',
      genre_ids: [1, 23],
      original_language: 'EN',
      popularity: 10,
      vote_count: 6,
    });
    expect(result[8]).toEqual({
      id: 9,
      title: 'Movie 3',
      poster_path: '/poster9.jpg',
      overview: 'Overview 3',
      release_date: '2022-02-22',
      vote_average: 6.5,
      backdrop_path: '/backdrop_path.jpg',
      genre_ids: [23, 5],
      original_language: 'EN',
      popularity: 10,
      vote_count: 6,
    });
    expect(result[9]).toEqual({
      id: 10,
      title: 'Movie 3',
      poster_path: '/poster10.jpg',
      overview: 'Overview 3',
      release_date: '2022-02-22',
      vote_average: 6.5,
      backdrop_path: '/backdrop_path.jpg',
      genre_ids: [23, 5],
      original_language: 'EN',
      popularity: 10,
      vote_count: 6,
    });
  });

  it('returns an empty array if input is empty', () => {
    const result = firstTenMoviesOrTVShowsWithPoster([]);
    expect(result.length).toBe(0);
  });

  it('returns an array of MovieOrTVShow objects with poster property', () => {
    const similarMoviesOrTvShows: MovieOrTVShow[] = [
      {
        id: 1,
        title: 'Movie 1',
        poster_path: '/poster1.jpg',
        overview: 'Overview 1',
        release_date: '2022-02-22',
        vote_average: 7.5,
        backdrop_path: '/backdrop_path.jpg',
        genre_ids: [1, 3, 5],
        original_language: 'EN',
        popularity: 10,
        vote_count: 6,
      },
      {
        id: 2,
        title: 'Movie 2',
        poster_path: null,
        overview: 'Overview 2',
        release_date: '2022-02-22',
        vote_average: 8.0,
        backdrop_path: '/backdrop_path.jpg',
        genre_ids: [1, 3, 5],
        original_language: 'EN',
        popularity: 10,
        vote_count: 6,
      },
      {
        id: 3,
        title: 'Movie 3',
        poster_path: null,
        overview: 'Overview 3',
        release_date: '2022-02-22',
        vote_average: 6.5,
        backdrop_path: '/backdrop_path.jpg',
        genre_ids: [1, 3, 5],
        original_language: 'EN',
        popularity: 10,
        vote_count: 6,
      },
    ];

    const result = firstTenMoviesOrTVShowsWithPoster(similarMoviesOrTvShows);

    expect(result.length).toBe(1);
    expect(result[0]).toEqual({
      id: 1,
      title: 'Movie 1',
      poster_path: '/poster1.jpg',
      overview: 'Overview 1',
      release_date: '2022-02-22',
      vote_average: 7.5,
      backdrop_path: '/backdrop_path.jpg',
      genre_ids: [1, 3, 5],
      original_language: 'EN',
      popularity: 10,
      vote_count: 6,
    });
  });
});
